# Site settings
title: ESUH
description: Economics Society at the University of Houston
baseurl: "/esuh" # the subpath of your site, e.g. /blog
url: "https://econsociety.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  research:
    output: true
    permalink: /research/:title/
  events:
    output: true
    permalink: /events/:title/
  dynamic_analyses:
    output: true
    permalink: /dynamic/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
